import random
number=random.randint(1,10)
chance=0
while chance<5:
    chance+=1
    userGuess=input("enter a number to check if it is the same no as generated by computer")
    userGuess=int(userGuess)
    if(userGuess==number):
        print("you are great guesser")
        break
    elif(userGuess<number):
        print("your number is smaller ")
    elif(userGuess>number):
        print("your number is greater")
    else:
        print("you lose")
        